//GENERATED BY GLSL_GEN
#ifndef VOXELBOUNCESHADER_HPP
#define VOXELBOUNCESHADER_HPP
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <fstream>
#include <GL/gl3w.h>
namespace asserts {
class VoxelBounceShader {
private:
	GLuint program_{0};
public:
	void Use() const { glUseProgram(program_); }
	GLuint Get() const { return program_; }
	VoxelBounceShader() = default;
	~VoxelBounceShader(){ if(program_ != 0) glDeleteProgram(program_); }
	VoxelBounceShader(const VoxelBounceShader &) = delete;
	VoxelBounceShader& operator= (const VoxelBounceShader &) = delete;
private:
	GLint unif_uVoxelDimension;
public:
	void Initialize() {
		GLuint shader;
		program_ = glCreateProgram();
		std::ifstream in; std::string str;
		char log[100000]; int success;
		in.open("shaders/voxel_bounce.comp");
		if(in.is_open()) {
			std::getline(in, str, '\0');
			in.close();
		} else {
			str.clear();
			printf("[GLSLGEN ERROR] failed to load shaders/voxel_bounce.comp\n");
		}
		const char *GL_COMPUTE_SHADER_src = str.c_str();
		shader = glCreateShader(GL_COMPUTE_SHADER);
		glShaderSource(shader, 1, &GL_COMPUTE_SHADER_src, nullptr);
		glCompileShader(shader);
		glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
		if(!success) {
			glGetShaderInfoLog(shader, 100000, nullptr, log);
			printf("[GLSLGEN ERROR] compile error in shaders/voxel_bounce.comp:\n%s\n", log);
		}
		glAttachShader(program_, shader);
		glLinkProgram(program_);
		glDeleteShader(shader);
		unif_uVoxelDimension = glGetUniformLocation(program_, "uVoxelDimension");
	}
	void SetUVoxelDimension(const glm::ivec3 &v) { glProgramUniform3iv(program_, unif_uVoxelDimension, 1, glm::value_ptr(v)); }
	GLint GetUVoxelDimensionLocation() const { return unif_uVoxelDimension; };
};
}
#endif
